"""
LiquidationFragilityUsd1 Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import LiquidationFragilityUsd1Strategy
except ImportError:
    from strategy import LiquidationFragilityUsd1Strategy

__all__ = [
    "LiquidationFragilityUsd1Strategy",
]
